Repository Rezyx-Inc/goodwork-backend, pull requests merged in 2025-02, with the labels that each got.

#406 Hot fix cards
  resources/views/site/explore_jobs.blade.php
  resources/views/site/explore_jobs_scripts.blade.php
Labels: Pending Review, ready to merge

#409 details ==> fix matche fields check
  Modules/Worker/Resources/views/dashboard/details/scripts.blade.php
Labels: ready to merge

#412 Add profession to worker signup & fix combining auth bugs
  Modules/Worker/Http/Controllers/WorkerAuthController.php
  app/Http/Controllers/SiteController.php
  public/backend/custom/js/script.js
  public/frontend/custom/js/script.js
  resources/views/site/Auth/login.blade.php
  resources/views/site/Auth/signup.blade.php
  routes/web.php
Labels: Pending Review

#411 modal responsive
  resources/views/site/explore_jobs_scripts.blade.php
Labels: Pending Review

#420 remove a sentence from worker profile
  Modules/Worker/Resources/views/dashboard/worker_profile.blade.php
Labels: Review validated

#425 Add job information to application message notifications
  Modules/Organization/Http/Controllers/OrganizationApplicationController.php
  Modules/Organization/Resources/views/organization/opportunitiesmanager/scripts/opportunitiesManagerScripts.blade.php
  Modules/Recruiter/Http/Controllers/ApplicationController.php
  Modules/Worker/Http/Controllers/WorkerController.php
Labels: ready to merge
